package com.dct.common.constant;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * 国家名称对应关系表.
 *
 * @author david
 */
public class CountryConstant {

    //英文全称对照.
    public static Map<String, String> fullCountryMap = new HashMap(1);

    //中文全称对照
    public static Map<String, String> cnNameMap = new HashMap<>(1);

    //英文简写对应中文
    public static Map<String, String> scCnameMap = new HashMap<>(1);

    static {
        Map<String, String> fullMap = new HashMap(1);

        fullMap.put("Papua New Guinea", "pg");
        fullMap.put("Cambodia", "kh");
        fullMap.put("Kazakhstan", "kz");
        fullMap.put("Paraguay", "py");
        fullMap.put("Åland Islands", "ax");
        fullMap.put("Bahamas", "bs");
        fullMap.put("Solomon Islands", "sb");
        fullMap.put("Montserrat", "ms");
        fullMap.put("Marshall Islands", "mh");
        fullMap.put("Mali", "ml");
        fullMap.put("Guadeloupe", "gp");
        fullMap.put("Panama", "pa");
        fullMap.put("Bonaire, Sint Eustatius and Saba", "bq");
        fullMap.put("Malysia", "my");
        fullMap.put("Tanzania, United Republic of", "tz");
        fullMap.put("Argentina", "ar");
        fullMap.put("Moldova", "md");
        fullMap.put("Seychelles", "sc");
        fullMap.put("Belize", "bz");
        fullMap.put("Zambia", "zm");
        fullMap.put("Bahrain", "bh");
        fullMap.put("Congo", "cg");
        fullMap.put("Guinea-Bissau", "gw");
        fullMap.put("Namibia", "na");
        fullMap.put("Finland", "fi");
        fullMap.put("Comoros", "km");
        fullMap.put("Faroe Islands", "fo");
        fullMap.put("Georgia", "ge");
        fullMap.put("Saint Kitts and Nevis", "kn");
        fullMap.put("Yemen", "ye");
        fullMap.put("Puerto Rico", "pr");
        fullMap.put("Eritrea", "er");
        fullMap.put("Viet Nam", "vn");
        fullMap.put("Aruba", "aw");
        fullMap.put("Madagascar", "mg");
        fullMap.put("Libya", "ly");
        fullMap.put("Svalbard and Jan Mayen", "sj");
        fullMap.put("Sweden", "se");
        fullMap.put("South Georgia and the South Sandwich Islands", "gs");
        fullMap.put("Cocos (Keeling) Islands", "cc");
        fullMap.put("Malawi", "mw");
        fullMap.put("Saint Helena, Ascension and Tristan da Cunha", "sh");
        fullMap.put("Andorra", "ad");
        fullMap.put("Liechtenstein", "li");
        fullMap.put("Poland", "pl");
        fullMap.put("Bangladesh|Bengal", "bd");
        fullMap.put("Jordan", "jo");
        fullMap.put("Bulgaria", "bg");
        fullMap.put("Tunisia", "tn");
        fullMap.put("Côte d'Ivoire", "ci");
        fullMap.put("United Arab Emirates", "ae");
        fullMap.put("Tuvalu", "tv");
        fullMap.put("Kenya", "ke");
        fullMap.put("French Polynesia", "pf");
        fullMap.put("Djibouti", "dj");
        fullMap.put("Lebanon", "lb");
        fullMap.put("Cuba", "cu");
        fullMap.put("Azerbaijan", "az");
        fullMap.put("Saint Lucia", "lc");
        fullMap.put("Mauritania", "mr");
        fullMap.put("Guernsey", "gg");
        fullMap.put("Mayotte", "yt");
        fullMap.put("San Marino", "sm");
        fullMap.put("Israel", "il");
        fullMap.put("Australia", "au");
        fullMap.put("Tajikistan", "tj");
        fullMap.put("Myanmar", "mm");
        fullMap.put("Cameroon", "cm");
        fullMap.put("Gibraltar", "gi");
        fullMap.put("Cyprus", "cy");
        fullMap.put("Northern Mariana Islands", "mp");
        fullMap.put("Iceland", "is");
        fullMap.put("Oman", "om");
        fullMap.put("Armenia", "am");
        fullMap.put("Gabon", "ga");
        fullMap.put("Luxembourg", "lu");
        fullMap.put("Brazil", "br");
        fullMap.put("Turks and Caicos Islands", "tc");
        fullMap.put("Algeria", "dz");
        fullMap.put("Cabo Verde", "cv");
        fullMap.put("Jersey", "je");
        fullMap.put("Slovenia", "si");
        fullMap.put("Antigua and Barbuda", "ag");
        fullMap.put("Colombia", "co");
        fullMap.put("Ecuador", "ec");
        fullMap.put("Iran (Islamic Republic of)", "ir");
        fullMap.put("United Kingdom", "gb");
        fullMap.put("Lao People's Democratic Republic", "la");
        fullMap.put("Vanuatu", "vu");
        fullMap.put("Eswatini", "sz");
        fullMap.put("United States Minor Outlying Islands", "um");
        fullMap.put("Italy", "it");
        fullMap.put("Honduras", "hn");
        fullMap.put("Antarctica", "aq");
        fullMap.put("Nauru", "nr");
        fullMap.put("Haiti", "ht");
        fullMap.put("Russian Federation", "ru");
        fullMap.put("Afghanistan", "af");
        fullMap.put("Burundi", "bi");
        fullMap.put("Singapore", "sg");
        fullMap.put("French Guiana", "gf");
        fullMap.put("American Samoa", "as");
        fullMap.put("Christmas Island", "cx");
        fullMap.put("Korea (Democratic People's Republic of)", "kp");
        fullMap.put("Netherlands", "nl");
        fullMap.put("China", "cn");
        fullMap.put("Martinique", "mq");
        fullMap.put("Saint Pierre and Miquelon", "pm");
        fullMap.put("Kyrgyzstan", "kg");
        fullMap.put("Bhutan", "bt");
        fullMap.put("Romania", "ro");
        fullMap.put("Togo", "tg");
        fullMap.put("Falkland Islands (Malvinas)", "fk");
        fullMap.put("Philippines", "ph");
        fullMap.put("Uzbekistan", "uz");
        fullMap.put("Pitcairn", "pn");
        fullMap.put("Zimbabwe", "zw");
        fullMap.put("British Indian Ocean Territory", "io");
        fullMap.put("Montenegro", "me");
        fullMap.put("Dominica", "dm");
        fullMap.put("Indonesia", "id");
        fullMap.put("Benin", "bj");
        fullMap.put("Angola", "ao");
        fullMap.put("Virgin Islands (British)", "vg");
        fullMap.put("Sudan", "sd");
        fullMap.put("Portugal", "pt");
        fullMap.put("Brunei Darussalam", "bn");
        fullMap.put("New Caledonia", "nc");
        fullMap.put("Grenada", "gd");
        fullMap.put("Greece", "gr");
        fullMap.put("Cayman Islands", "ky");
        fullMap.put("Congo (Democratic Republic of the)", "cd");
        fullMap.put("Latvia", "lv");
        fullMap.put("Mongolia", "mn");
        fullMap.put("Morocco", "ma");
        fullMap.put("Guatemala", "gt");
        fullMap.put("Guyana", "gy");
        fullMap.put("Iraq", "iq");
        fullMap.put("Chile", "cl");
        fullMap.put("Nepal", "np");
        fullMap.put("Heard Island and McDonald Islands", "hm");
        fullMap.put("Isle of Man", "im");
        fullMap.put("Ukraine", "ua");
        fullMap.put("Ghana", "gh");
        fullMap.put("Holy See", "va");
        fullMap.put("Anguilla", "ai");
        fullMap.put("India", "in");
        fullMap.put("Canada", "ca");
        fullMap.put("Maldives", "mv");
        fullMap.put("Turkey", "tr");
        fullMap.put("Belgium", "be");
        fullMap.put("South Africa", "za");
        fullMap.put("Trinidad and Tobago", "tt");
        fullMap.put("Bermuda", "bm");
        fullMap.put("Central African Republic", "cf");
        fullMap.put("Jamaica", "jm");
        fullMap.put("Peru", "pe");
        fullMap.put("Venezuela (Bolivarian Republic of)", "ve");
        fullMap.put("Turkmenistan", "tm");
        fullMap.put("Germany", "de");
        fullMap.put("Tokelau", "tk");
        fullMap.put("Fiji", "fj");
        fullMap.put("Hong Kong", "hk");
        fullMap.put("Guinea", "gn");
        fullMap.put("Chad", "td");
        fullMap.put("Somalia", "so");
        fullMap.put("Sao Tome and Principe", "st");
        fullMap.put("Thailand", "th");
        fullMap.put("Equatorial Guinea", "gq");
        fullMap.put("Kiribati", "ki");
        fullMap.put("Costa Rica", "cr");
        fullMap.put("Saint Martin", "mf");
        fullMap.put("Kuwait", "kw");
        fullMap.put("Nigeria", "ng");
        fullMap.put("Palestine", "bl");
        fullMap.put("Croatia", "hr");
        fullMap.put("Syrian Arab Republic", "sy");
        fullMap.put("Uruguay", "uy");
        fullMap.put("Sri Lanka", "lk");
        fullMap.put("Cook Islands", "ck");
        fullMap.put("Timor-Leste", "tl");
        fullMap.put("Switzerland", "ch");
        fullMap.put("Samoa", "ws");
        fullMap.put("Spain", "es");
        fullMap.put("Liberia", "lr");
        fullMap.put("Burkina Faso", "bf");
        fullMap.put("Swaziland", "sz");
        fullMap.put("Palau", "pw");
        fullMap.put("Estonia", "ee");
        fullMap.put("Wallis and Futuna", "wf");
        fullMap.put("Niue", "nu");
        fullMap.put("Austria", "at");
        fullMap.put("Mozambique", "mz");
        fullMap.put("El Salvador", "sv");
        fullMap.put("Monaco", "mc");
        fullMap.put("Guam", "gu");
        fullMap.put("Lesotho", "ls");
        fullMap.put("Tonga", "to");
        fullMap.put("Western Sahara", "eh");
        fullMap.put("Hungary", "hu");
        fullMap.put("Réunion", "re");
        fullMap.put("South Sudan", "ss");
        fullMap.put("Japan", "jp");
        fullMap.put("Curacao", "cw");
        fullMap.put("Belarus", "by");
        fullMap.put("Mauritius", "mu");
        fullMap.put("Bouvet Island", "bv");
        fullMap.put("Norfolk Island", "nf");
        fullMap.put("Virgin Islands (U.S.)", "vi");
        fullMap.put("Albania", "al");
        fullMap.put("Bolivia", "bo");
        fullMap.put("New Zealand", "nz");
        fullMap.put("Sint Maarten (Dutch part)", "sx");
        fullMap.put("Senegal", "sn");
        fullMap.put("Micronesia", "fm");
        fullMap.put("Ethiopia", "et");
        fullMap.put("Macedonia (the former Yugoslav Republic of)", "mk");
        fullMap.put("Czechia", "cz");
        fullMap.put("United States","us");
        fullMap.put("Venezuela","ve");
        fullMap.put("Tanzania","tz");
        fullMap.put("Bangladesh","bd");
        fullMap.put("Cape Verde","cv");
        fullMap.put("Curaçao","cw");
        fullMap.put("Vietnam","vn");
        fullMap.put("Kosovo","xk");
        fullMap.put("Malaysia","my");
        fullMap.put("São Tomé & Príncipe","st");
        fullMap.put("Sint Maarten","sx");
        fullMap.put("United States of America", "us");
        fullMap.put("Egypt", "eg");
        fullMap.put("Sierra Leone", "sl");
        fullMap.put("Malta", "mt");
        fullMap.put("Saudi Arabia", "sa");
        fullMap.put("Pakistan", "pk");
        fullMap.put("South Korea","kr");
        fullMap.put("Laos","la");
        fullMap.put("North Macedonia","mk");
        fullMap.put("Myanmar (Burma)","mm");
        fullMap.put("Gambia", "gm");
        fullMap.put("Ireland", "ie");
        fullMap.put("Qatar", "qa");
        fullMap.put("Slovakia", "sk");
        fullMap.put("France", "fr");
        fullMap.put("Serbia", "rs");
        fullMap.put("Lithuania", "lt");
        fullMap.put("Bosnia and Herzegovina", "ba");
        fullMap.put("Korea (Republic of)", "kr");
        fullMap.put("Taiwan, Province of China", "tw");
        fullMap.put("Niger", "ne");
        fullMap.put("Rwanda", "rw");
        fullMap.put("French Southern Territories", "tf");
        fullMap.put("Barbados", "bb");
        fullMap.put("Nicaragua", "ni");
        fullMap.put("Norway", "no");
        fullMap.put("Saint Vincent and the Grenadines", "vc");
        fullMap.put("Botswana", "bw");
        fullMap.put("Macao", "mo");
        fullMap.put("Dominican Republic", "do");
        fullMap.put("Denmark", "dk");
        fullMap.put("Mexico", "mx");
        fullMap.put("Uganda", "ug");
        fullMap.put("Suriname", "sr");
        fullMap.put("Greenland", "gl");
        fullMap.put("Bosnia & Herzegovina", "ba");
        fullMap.put("Antigua & Barbuda", "ag");
        fullMap.put("British Virgin Islands", "vg");
        fullMap.put("Congo - Brazzaville", "cg");
        fullMap.put("Congo - Kinshasa", "cd");
        fullMap.put("Côte d’Ivoire", "ci");
        fullMap.put("Georgia", "ge");
        fullMap.put("St Kitts & Nevis", "kn");
        fullMap.put("St Lucia", "lc");
        fullMap.put("Trinidad & Tobago", "tt");
        fullMap.put("Turks & Caicos Islands", "tc");
        fullMap.put("Vatican City", "va");
        fullCountryMap = Collections.unmodifiableMap(fullMap);

        Map<String, String> cnameMap = new HashMap<>(1);

        cnameMap.put("泰国", "th");
        cnameMap.put("巴西", "br");
        cnameMap.put("斯威士兰", "sz");
        cnameMap.put("安道尔", "ad");
        cnameMap.put("委内瑞拉", "ve");
        cnameMap.put("蒙古国", "mn");
        cnameMap.put("约旦", "jo");
        cnameMap.put("新西兰", "nz");
        cnameMap.put("柬埔寨", "kh");
        cnameMap.put("布隆迪", "bi");
        cnameMap.put("贝宁", "bj");
        cnameMap.put("加纳", "gh");
        cnameMap.put("直布罗陀", "gi");
        cnameMap.put("科特迪瓦", "ci");
        cnameMap.put("挪威", "no");
        cnameMap.put("阿根廷", "ar");
        cnameMap.put("纳米比亚", "na");
        cnameMap.put("摩尔多瓦", "md");
        cnameMap.put("特立尼达和多巴哥", "tt");
        cnameMap.put("圣马丁", "sx");
        cnameMap.put("库拉索", "cw");
        cnameMap.put("东帝汶", "tl");
        cnameMap.put("乌兹别克斯坦", "uz");
        cnameMap.put("卡塔尔", "qa");
        cnameMap.put("韩国", "kr");
        cnameMap.put("马绍尔群岛", "mh");
        cnameMap.put("巴林", "bh");
        cnameMap.put("哥伦比亚", "co");
        cnameMap.put("南极洲", "aq");
        cnameMap.put("德国", "de");
        cnameMap.put("泽西", "je");
        cnameMap.put("立陶宛", "lt");
        cnameMap.put("马耳他", "mt");
        cnameMap.put("英国", "gb");
        cnameMap.put("圣文森特和格林纳丁斯", "vc");
        cnameMap.put("巴勒斯坦", "bl");
        cnameMap.put("所罗门群岛", "sb");
        cnameMap.put("瑞士", "ch");
        cnameMap.put("奥地利", "at");
        cnameMap.put("马尔代夫", "mv");
        cnameMap.put("意大利", "it");
        cnameMap.put("加蓬", "ga");
        cnameMap.put("科摩罗", "cd");
        cnameMap.put("瓦努阿图", "vu");
        cnameMap.put("芬兰", "fi");
        cnameMap.put("土耳其", "tr");
        cnameMap.put("阿鲁巴", "aw");
        cnameMap.put("法属圣马丁", "mf");
        cnameMap.put("托克劳", "tk");
        cnameMap.put("科索沃","xk");
        cnameMap.put("比利时", "be");
        cnameMap.put("多米尼加", "do");
        cnameMap.put("密克罗尼西亚", "fm");
        cnameMap.put("圭亚那", "gy");
        cnameMap.put("根西", "gg");
        cnameMap.put("索马里", "so");
        cnameMap.put("埃及", "eg");
        cnameMap.put("利比亚", "ly");
        cnameMap.put("叙利亚", "sy");
        cnameMap.put("巴巴多斯", "bb");
        cnameMap.put("爱尔兰", "ie");
        cnameMap.put("中国", "cn");
        cnameMap.put("阿尔巴尼亚", "al");
        cnameMap.put("澳大利亚", "au");
        cnameMap.put("佛得角", "cv");
        cnameMap.put("萨摩亚", "ws");
        cnameMap.put("巴勒斯坦", "ps");
        cnameMap.put("赤道几内亚", "gq");
        cnameMap.put("阿曼", "om");
        cnameMap.put("巴基斯坦", "pk");
        cnameMap.put("卢森堡", "lu");
        cnameMap.put("海地", "ht");
        cnameMap.put("古巴", "cu");
        cnameMap.put("斯瓦尔巴和扬马延", "sj");
        cnameMap.put("澳门", "mo");
        cnameMap.put("黎巴嫩", "lb");
        cnameMap.put("哥斯达黎加", "cr");
        cnameMap.put("法属圭亚那", "gf");
        cnameMap.put("奥兰", "ax");
        cnameMap.put("尼泊尔", "np");
        cnameMap.put("罗马尼亚", "ro");
        cnameMap.put("卢旺达", "rw");
        cnameMap.put("利比里亚", "lr");
        cnameMap.put("几内亚", "gn");
        cnameMap.put("纽埃", "nu");
        cnameMap.put("北马其顿", "mk");
        cnameMap.put("安哥拉", "ao");
        cnameMap.put("汤加", "to");
        cnameMap.put("吉布提", "dj");
        cnameMap.put("梵蒂冈城", "va");
        cnameMap.put("库克群岛", "ck");
        cnameMap.put("以色列", "il");
        cnameMap.put("开曼群岛", "ky");
        cnameMap.put("墨西哥", "mx");
        cnameMap.put("危地马拉", "gt");
        cnameMap.put("希腊", "gr");
        cnameMap.put("阿富汗", "af");
        cnameMap.put("多米尼克", "dm");
        cnameMap.put("亚美尼亚", "am");
        cnameMap.put("捷克", "cz");
        cnameMap.put("百慕大", "bm");
        cnameMap.put("新喀里多尼亚", "nc");
        cnameMap.put("保加利亚", "bg");
        cnameMap.put("匈牙利", "hu");
        cnameMap.put("波兰", "pl");
        cnameMap.put("英属印度洋领地", "io");
        cnameMap.put("中国香港", "hk");
        cnameMap.put("法国", "fr");
        cnameMap.put("印尼", "id");
        cnameMap.put("俄罗斯", "ru");
        cnameMap.put("斯里兰卡", "lk");
        cnameMap.put("荷兰", "nl");
        cnameMap.put("斯洛文尼亚", "si");
        cnameMap.put("瑞典", "se");
        cnameMap.put("摩洛哥", "ma");
        cnameMap.put("聖文森與格瑞那丁", "vc");
        cnameMap.put("拉脫維亞", "lv");
        cnameMap.put("中非", "cf");
        cnameMap.put("缅甸", "mm");
        cnameMap.put("基里巴斯", "ki");
        cnameMap.put("冰岛", "is");
        cnameMap.put("南乔治亚和南桑威奇群岛", "gs");
        cnameMap.put("突尼斯", "tn");
        cnameMap.put("乍得", "td");
        cnameMap.put("智利", "cl");
        cnameMap.put("刚果", "cg");
        cnameMap.put("刚果民主共和国", "cd");
        cnameMap.put("马拉维", "mw");
        cnameMap.put("巴布亚新几内亚", "pg");
        cnameMap.put("伯利兹", "bz");
        cnameMap.put("南非", "za");
        cnameMap.put("圣多美和普林西比", "st");
        cnameMap.put("马恩岛", "im");
        cnameMap.put("马来西亚", "my");
        cnameMap.put("马里", "ml");
        cnameMap.put("巴哈马", "bs");
        cnameMap.put("葡萄牙", "pt");
        cnameMap.put("福克兰群岛", "fk");
        cnameMap.put("津巴布韦", "zw");
        cnameMap.put("菲律宾", "ph");
        cnameMap.put("孟加拉国", "bd");
        cnameMap.put("多哥", "tg");
        cnameMap.put("留尼汪", "re");
        cnameMap.put("赞比亚", "zm");
        cnameMap.put("瓜德罗普", "gp");
        cnameMap.put("文莱", "bn");
        cnameMap.put("克罗地亚", "hr");
        cnameMap.put("尼日利亚", "ng");
        cnameMap.put("莫桑比克", "mz");
        cnameMap.put("朝鲜", "kp");
        cnameMap.put("厄立特里亚", "er");
        cnameMap.put("巴拉圭", "py");
        cnameMap.put("伊拉克", "iq");
        cnameMap.put("莱索托", "ls");
        cnameMap.put("越南", "vn");
        cnameMap.put("美国", "us");
        cnameMap.put("梵蒂冈", "va");
        cnameMap.put("肯尼亚", "ke");
        cnameMap.put("圣皮埃尔和密克隆", "pm");
        cnameMap.put("尼加拉瓜", "ni");
        cnameMap.put("法属波利尼西亚", "pf");
        cnameMap.put("巴拿马", "pa");
        cnameMap.put("西撒哈拉", "eh");
        cnameMap.put("吉尔吉斯斯坦", "kg");
        cnameMap.put("英属维尔京群岛", "vg");
        cnameMap.put("埃塞俄比亚", "et");
        cnameMap.put("摩纳哥", "mc");
        cnameMap.put("老挝", "la");
        cnameMap.put("帕劳", "pw");
        cnameMap.put("诺福克岛", "nf");
        cnameMap.put("圣卢西亚", "lc");
        cnameMap.put("印度", "in");
        cnameMap.put("塞舌尔", "sc");
        cnameMap.put("毛里塔尼亚", "mr");
        cnameMap.put("安提瓜和巴布达", "ag");
        cnameMap.put("蒙特塞拉特", "ms");
        cnameMap.put("伊朗", "ir");
        cnameMap.put("瑙鲁", "nr");
        cnameMap.put("白俄罗斯", "by");
        cnameMap.put("格陵兰", "gl");
        cnameMap.put("圣基茨和尼维斯", "kn");
        cnameMap.put("苏丹", "sd");
        cnameMap.put("斯洛伐克", "sk");
        cnameMap.put("阿尔及利亚", "dz");
        cnameMap.put("也门", "ye");
        cnameMap.put("波斯尼亚和黑塞哥维那", "ba");
        cnameMap.put("尼日尔", "ne");
        cnameMap.put("格林纳达", "gd");
        cnameMap.put("拉脱维亚", "lv");
        cnameMap.put("喀麦隆", "cm");
        cnameMap.put("赫德岛和麦克唐纳群岛", "hm");
        cnameMap.put("法属南方和南极洲领地", "tf");
        cnameMap.put("法罗群岛", "fo");
        cnameMap.put("格鲁吉亚", "ge");
        cnameMap.put("土库曼斯坦", "tm");
        cnameMap.put("关岛", "gu");
        cnameMap.put("坦桑尼亚", "tz");
        cnameMap.put("毛里求斯", "mu");
        cnameMap.put("丹麦", "dk");
        cnameMap.put("瓦利斯和富图纳", "wf");
        cnameMap.put("塞尔维亚", "rs");
        cnameMap.put("列支敦士登", "li");
        cnameMap.put("波多黎各", "pr");
        cnameMap.put("洪都拉斯", "hn");
        cnameMap.put("美属萨摩亚", "as");
        cnameMap.put("布基纳法索", "bf");
        cnameMap.put("萨尔瓦多", "sv");
        cnameMap.put("美属维尔京群岛", "vi");
        cnameMap.put("特克斯和凯科斯群岛", "tc");
        cnameMap.put("沙特阿拉伯", "sa");
        cnameMap.put("秘鲁", "pe");
        cnameMap.put("荷兰加勒比区", "bq");
        cnameMap.put("南苏丹", "ss");
        cnameMap.put("厄瓜多尔", "ec");
        cnameMap.put("玻利维亚", "bo");
        cnameMap.put("马约特", "yt");
        cnameMap.put("斐济", "fj");
        cnameMap.put("阿联酋", "ae");
        cnameMap.put("中国台湾省", "tw");
        cnameMap.put("圣诞岛", "cx");
        cnameMap.put("塞浦路斯", "cy");
        cnameMap.put("皮特凯恩群岛", "pn");
        cnameMap.put("圣马力诺", "sm");
        cnameMap.put("不丹", "bt");
        cnameMap.put("博茨瓦纳", "bw");
        cnameMap.put("马提尼克", "mq");
        cnameMap.put("几内亚比绍", "gw");
        cnameMap.put("布韦岛", "bv");
        cnameMap.put("哈萨克斯坦", "kz");
        cnameMap.put("塞拉利昂", "sl");
        cnameMap.put("阿塞拜疆", "az");
        cnameMap.put("黑山", "me");
        cnameMap.put("西班牙", "es");
        cnameMap.put("乌克兰", "ua");
        cnameMap.put("乌拉圭", "uy");
        cnameMap.put("安圭拉", "ai");
        cnameMap.put("苏里南", "sr");
        cnameMap.put("塔吉克斯坦", "tj");
        cnameMap.put("乌干达", "ug");
        cnameMap.put("加拿大", "ca");
        cnameMap.put("日本", "jp");
        cnameMap.put("爱沙尼亚", "ee");
        cnameMap.put("图瓦卢", "tv");
        cnameMap.put("马达加斯加", "mg");
        cnameMap.put("冈比亚", "gm");
        cnameMap.put("美国本土外小岛屿", "um");
        cnameMap.put("北马里亚纳群岛", "mp");
        cnameMap.put("新加坡", "sg");
        cnameMap.put("塞内加尔", "sn");
        cnameMap.put("科威特", "kw");
        cnameMap.put("牙买加", "jm");

        cnNameMap = Collections.unmodifiableMap(cnameMap);

        Map<String, String> scNameMap = new HashMap<>();
        scNameMap.put("pr", "波多黎各");
        scNameMap.put("ps", "巴勒斯坦");
        scNameMap.put("pt", "葡萄牙");
        scNameMap.put("pw", "帕劳");
        scNameMap.put("py", "巴拉圭");
        scNameMap.put("qa", "卡塔尔");
        scNameMap.put("ad", "安道尔");
        scNameMap.put("ae", "阿联酋");
        scNameMap.put("af", "阿富汗");
        scNameMap.put("ag", "安提瓜和巴布达");
        scNameMap.put("ai", "安圭拉");
        scNameMap.put("al", "阿尔巴尼亚");
        scNameMap.put("am", "亚美尼亚");
        scNameMap.put("ao", "安哥拉");
        scNameMap.put("aq", "南极洲");
        scNameMap.put("ar", "阿根廷");
        scNameMap.put("as", "美属萨摩亚");
        scNameMap.put("at", "奥地利");
        scNameMap.put("re", "留尼汪");
        scNameMap.put("au", "澳大利亚");
        scNameMap.put("aw", "阿鲁巴");
        scNameMap.put("ax", "奥兰");
        scNameMap.put("az", "阿塞拜疆");
        scNameMap.put("ro", "罗马尼亚");
        scNameMap.put("ba", "波斯尼亚和黑塞哥维那");
        scNameMap.put("bb", "巴巴多斯");
        scNameMap.put("rs", "塞尔维亚");
        scNameMap.put("bd", "孟加拉国");
        scNameMap.put("be", "比利时");
        scNameMap.put("ru", "俄罗斯");
        scNameMap.put("bf", "布基纳法索");
        scNameMap.put("bg", "保加利亚");
        scNameMap.put("rw", "卢旺达");
        scNameMap.put("bh", "巴林");
        scNameMap.put("bi", "布隆迪");
        scNameMap.put("bj", "贝宁");
        scNameMap.put("bl", "巴勒斯坦");
        scNameMap.put("bm", "百慕大");
        scNameMap.put("bn", "文莱");
        scNameMap.put("bo", "玻利维亚");
        scNameMap.put("sa", "沙特阿拉伯");
        scNameMap.put("sb", "所罗门群岛");
        scNameMap.put("bq", "荷兰加勒比区");
        scNameMap.put("br", "巴西");
        scNameMap.put("sc", "塞舌尔");
        scNameMap.put("bs", "巴哈马");
        scNameMap.put("sd", "苏丹");
        scNameMap.put("se", "瑞典");
        scNameMap.put("bt", "不丹");
        scNameMap.put("bv", "布韦岛");
        scNameMap.put("sg", "新加坡");
        scNameMap.put("sh", "圣巴泰勒米");
        scNameMap.put("bw", "博茨瓦纳");
        scNameMap.put("si", "斯洛文尼亚");
        scNameMap.put("sj", "斯瓦尔巴和扬马延");
        scNameMap.put("by", "白俄罗斯");
        scNameMap.put("bz", "伯利兹");
        scNameMap.put("sk", "斯洛伐克");
        scNameMap.put("sl", "塞拉利昂");
        scNameMap.put("sm", "圣马力诺");
        scNameMap.put("sn", "塞内加尔");
        scNameMap.put("so", "索马里");
        scNameMap.put("ca", "加拿大");
        scNameMap.put("sr", "苏里南");
        scNameMap.put("ss", "南苏丹");
        scNameMap.put("cc", "圣诞岛");
        scNameMap.put("st", "圣多美和普林西比");
        scNameMap.put("cd", "科摩罗");
        scNameMap.put("cf", "中非");
        scNameMap.put("sv", "萨尔瓦多");
        scNameMap.put("cg", "科摩罗");
        scNameMap.put("sx", "圣马丁");
        scNameMap.put("ch", "瑞士");
        scNameMap.put("sy", "叙利亚");
        scNameMap.put("ci", "科特迪瓦");
        scNameMap.put("sz", "斯威士兰");
        scNameMap.put("ck", "库克群岛");
        scNameMap.put("cl", "智利");
        scNameMap.put("cm", "喀麦隆");
        scNameMap.put("cn", "中国");
        scNameMap.put("co", "哥伦比亚");
        scNameMap.put("tc", "特克斯和凯科斯群岛");
        scNameMap.put("cr", "哥斯达黎加");
        scNameMap.put("td", "乍得");
        scNameMap.put("cu", "古巴");
        scNameMap.put("tf", "法属南方和南极洲领地");
        scNameMap.put("tg", "多哥");
        scNameMap.put("cv", "佛得角");
        scNameMap.put("th", "泰国");
        scNameMap.put("cw", "库拉索");
        scNameMap.put("cx", "圣诞岛");
        scNameMap.put("tj", "塔吉克斯坦");
        scNameMap.put("cy", "塞浦路斯");
        scNameMap.put("tk", "托克劳");
        scNameMap.put("cz", "捷克");
        scNameMap.put("tl", "东帝汶");
        scNameMap.put("tm", "土库曼斯坦");
        scNameMap.put("tn", "突尼斯");
        scNameMap.put("to", "汤加");
        scNameMap.put("tr", "土耳其");
        scNameMap.put("tt", "特立尼达和多巴哥");
        scNameMap.put("de", "德国");
        scNameMap.put("tv", "图瓦卢");
        scNameMap.put("tw", "中国台湾省");
        scNameMap.put("dj", "吉布提");
        scNameMap.put("tz", "坦桑尼亚");
        scNameMap.put("dk", "丹麦");
        scNameMap.put("dm", "多米尼克");
        scNameMap.put("do", "多米尼加");
        scNameMap.put("ua", "乌克兰");
        scNameMap.put("ug", "乌干达");
        scNameMap.put("dz", "阿尔及利亚");
        scNameMap.put("um", "美国本土外小岛屿");
        scNameMap.put("ec", "厄瓜多尔");
        scNameMap.put("us", "美国");
        scNameMap.put("ee", "爱沙尼亚");
        scNameMap.put("eg", "埃及");
        scNameMap.put("eh", "西撒哈拉");
        scNameMap.put("uy", "乌拉圭");
        scNameMap.put("uz", "乌兹别克斯坦");
        scNameMap.put("va", "梵蒂冈");
        scNameMap.put("vc", "圣文森特和格林纳丁斯");
        scNameMap.put("er", "厄立特里亚");
        scNameMap.put("es", "西班牙");
        scNameMap.put("et", "埃塞俄比亚");
        scNameMap.put("ve", "委内瑞拉");
        scNameMap.put("vg", "英属维尔京群岛");
        scNameMap.put("vi", "美属维尔京群岛");
        scNameMap.put("vn", "越南");
        scNameMap.put("vu", "瓦努阿图");
        scNameMap.put("fi", "芬兰");
        scNameMap.put("fj", "斐济");
        scNameMap.put("fk", "福克兰群岛");
        scNameMap.put("fm", "密克罗尼西亚联邦");
        scNameMap.put("fo", "法罗群岛");
        scNameMap.put("fr", "法国");
        scNameMap.put("wf", "瓦利斯和富图纳");
        scNameMap.put("ga", "加蓬");
        scNameMap.put("gb", "英国");
        scNameMap.put("ws", "萨摩亚");
        scNameMap.put("gd", "格林纳达");
        scNameMap.put("ge", "格鲁吉亚");
        scNameMap.put("gf", "法属圭亚那");
        scNameMap.put("gg", "根西");
        scNameMap.put("gh", "加纳");
        scNameMap.put("gi", "直布罗陀");
        scNameMap.put("gl", "格陵兰");
        scNameMap.put("gm", "冈比亚");
        scNameMap.put("gn", "几内亚");
        scNameMap.put("gp", "瓜德罗普");
        scNameMap.put("gq", "赤道几内亚");
        scNameMap.put("gr", "希腊");
        scNameMap.put("gs", "南乔治亚和南桑威奇群岛");
        scNameMap.put("gt", "危地马拉");
        scNameMap.put("gu", "关岛");
        scNameMap.put("gw", "几内亚比绍");
        scNameMap.put("gy", "圭亚那");
        scNameMap.put("hk", "中国香港");
        scNameMap.put("hm", "赫德岛和麦克唐纳群岛");
        scNameMap.put("hn", "洪都拉斯");
        scNameMap.put("hr", "克罗地亚");
        scNameMap.put("ht", "海地");
        scNameMap.put("ye", "也门");
        scNameMap.put("hu", "匈牙利");
        scNameMap.put("yt", "马约特");
        scNameMap.put("id", "印尼");
        scNameMap.put("ie", "爱尔兰");
        scNameMap.put("il", "以色列");
        scNameMap.put("im", "马恩岛");
        scNameMap.put("in", "印度");
        scNameMap.put("io", "英属印度洋领地");
        scNameMap.put("za", "南非");
        scNameMap.put("iq", "伊拉克");
        scNameMap.put("ir", "伊朗");
        scNameMap.put("is", "冰岛");
        scNameMap.put("it", "意大利");
        scNameMap.put("zm", "赞比亚");
        scNameMap.put("je", "泽西");
        scNameMap.put("zw", "津巴布韦");
        scNameMap.put("jm", "牙买加");
        scNameMap.put("jo", "约旦");
        scNameMap.put("jp", "日本");
        scNameMap.put("ke", "肯尼亚");
        scNameMap.put("kg", "吉尔吉斯斯坦");
        scNameMap.put("kh", "柬埔寨");
        scNameMap.put("ki", "基里巴斯");
        scNameMap.put("km", "科摩罗");
        scNameMap.put("kn", "圣基茨和尼维斯");
        scNameMap.put("kp", "朝鲜");
        scNameMap.put("kr", "韩国");
        scNameMap.put("kw", "科威特");
        scNameMap.put("ky", "开曼群岛");
        scNameMap.put("kz", "哈萨克斯坦");
        scNameMap.put("la", "老挝");
        scNameMap.put("lb", "黎巴嫩");
        scNameMap.put("lc", "圣卢西亚");
        scNameMap.put("li", "列支敦士登");
        scNameMap.put("lk", "斯里兰卡");
        scNameMap.put("lr", "利比里亚");
        scNameMap.put("ls", "莱索托");
        scNameMap.put("lt", "立陶宛");
        scNameMap.put("lu", "卢森堡");
        scNameMap.put("lv", "拉脱维亚");
        scNameMap.put("ly", "利比亚");
        scNameMap.put("ma", "摩洛哥");
        scNameMap.put("mc", "摩纳哥");
        scNameMap.put("md", "摩尔多瓦");
        scNameMap.put("me", "黑山");
        scNameMap.put("mf", "法属圣马丁");
        scNameMap.put("mg", "马达加斯加");
        scNameMap.put("mh", "马绍尔群岛");
        scNameMap.put("mk", "北马其顿");
        scNameMap.put("ml", "马里");
        scNameMap.put("mm", "缅甸");
        scNameMap.put("mn", "蒙古国");
        scNameMap.put("mo", "澳门");
        scNameMap.put("mp", "北马里亚纳群岛");
        scNameMap.put("mq", "马提尼克");
        scNameMap.put("mr", "毛里塔尼亚");
        scNameMap.put("ms", "蒙特塞拉特");
        scNameMap.put("mt", "马耳他");
        scNameMap.put("mu", "毛里求斯");
        scNameMap.put("mv", "马尔代夫");
        scNameMap.put("mw", "马拉维");
        scNameMap.put("mx", "墨西哥");
        scNameMap.put("my", "马来西亚");
        scNameMap.put("mz", "莫桑比克");
        scNameMap.put("na", "纳米比亚");
        scNameMap.put("nc", "新喀里多尼亚");
        scNameMap.put("ne", "尼日尔");
        scNameMap.put("nf", "诺福克岛");
        scNameMap.put("ng", "尼日利亚");
        scNameMap.put("ni", "尼加拉瓜");
        scNameMap.put("nl", "荷兰");
        scNameMap.put("no", "挪威");
        scNameMap.put("np", "尼泊尔");
        scNameMap.put("nr", "瑙鲁");
        scNameMap.put("nu", "纽埃");
        scNameMap.put("nz", "新西兰");
        scNameMap.put("om", "阿曼");
        scNameMap.put("pa", "巴拿马");
        scNameMap.put("pe", "秘鲁");
        scNameMap.put("pf", "法属波利尼西亚");
        scNameMap.put("pg", "巴布亚新几内亚");
        scNameMap.put("ph", "菲律宾");
        scNameMap.put("pk", "巴基斯坦");
        scNameMap.put("pl", "波兰");
        scNameMap.put("pm", "圣皮埃尔和密克隆");
        scNameMap.put("pn", "皮特凯恩群岛");
        scNameMap.put("cg", "刚果布");
        scNameMap.put("cd", "刚果金");

        scCnameMap = Collections.unmodifiableMap(scNameMap);

    }


}
