spring:
  application:
    name: dct
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "


logging:
  level:
    com.dct: info
  config: classpath:logback-${spring.profiles.active}.xml

abb:
  abb: 12